# Generated by Django 4.2.4 on 2023-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
